name: Security

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Minimum permissions required for this workflow
permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest # The job will run on an updated Ubuntu environment

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4 # Action to clone the repository in the execution environment

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Action to set up the Node.js version
        with:
          node-version: '20' # Specifies the Node.js version to use

      - name: Install dependencies with npm
        run: npm ci # Cleanly install the project dependencies

      - name: Security audit on dependencies
        run: npm audit --audit-level=high # Run a security audit to detect critical vulnerabilities

      - name: Run unit tests
        run: npm test -- --watch=false --browsers=ChromeHeadless # Run unit tests in a headless browser

      - name: Build the application in production mode
        run: npm run build -- --configuration=production # Build the application in production mode
